zuul:
  routes:
    estrategia-app:
      path: /api/v1/**
#    estrategia:
#      path: /estrategia/**
#      url: http://localhost:9090/api/v1

spring:
  mvc:
    servlet:
      load-on-startup: 1
  application:
    name: zuul-api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

  instance:
    preferIpAddress: true