version: '3'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    environment:
      - "http.cors.allow-origin=*"
    volumes:
      - data01:/data
    ports:
      - 5200:5000
      - 6379:6379
      
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: estrategia
      POSTGRES_PASSWORD: estrategia
      POSTGRES_USER: estrategia

  # front:
  #   image: pos-estrategia-front
  #   ports:
  #     - 4200:80

  # back:
  #   image: pos-estrategia-api
  #   ports:
  #     - 8080:8080

  registry:
    image: registry
    ports:
      - 5000:5000

volumes:
  data01:
    driver: local
  postgres-data:
