# Separei caso o Desenvolvedor queira somente o Banco e executar a APP pelo eclipse
version: '3'
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: estrategia
      POSTGRES_PASSWORD: estrategia
      POSTGRES_USER: estrategia

volumes:
  postgres-data:
